#!/usr/bin/env python3
"""Build target-specific GraXpert package assets."""

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import zipfile
from collections import defaultdict
from email.parser import Parser
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
PACKAGE_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_SOURCE = PACKAGE_ROOT / "package"
PACKAGE_ID = "graxpert"
TARGETS = ("linux-clang-x86_64", "windows-msvc-x86_64")

sys.path.insert(0, str(REPO_ROOT / "tools"))

from afternight_repo.package_tools import build_package, read_json, sha256_file  # noqa: E402


def is_universal_wheel(name):
    return name.endswith("-none-any.whl")


def canonicalize_name(name):
    return name.strip().lower().replace("_", "-")


def read_wheel_metadata(wheel_path):
    with zipfile.ZipFile(wheel_path) as archive:
        metadata_name = next(
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA")
        )
        metadata = Parser().parsestr(
            archive.read(metadata_name).decode("utf-8", "replace")
        )

    package_name = metadata.get("Name")
    version = metadata.get("Version")
    if not package_name or not version:
        raise RuntimeError(f"Wheel {wheel_path} is missing Name metadata")
    return canonicalize_name(package_name), version.strip()


def read_wheel_package_name(wheel_path):
    package_name, _ = read_wheel_metadata(wheel_path)
    return package_name


def target_specificity(name, target):
    if target == "linux-clang-x86_64" and ("manylinux" in name or "linux_x86_64" in name):
        return 2
    if target == "windows-msvc-x86_64" and "win_amd64" in name:
        return 2
    if is_universal_wheel(name):
        return 1
    return 0


def copy_package_source(destination):
    def ignore(directory, names):
        del directory
        ignored = {"__pycache__", "wheelhouse"}
        ignored.update(name for name in names if name.endswith((".pyc", ".pyo")))
        return ignored

    shutil.copytree(PACKAGE_SOURCE, destination, ignore=ignore)
    (destination / "wheelhouse").mkdir(parents=True, exist_ok=True)


def copy_existing_wheelhouse(source_wheelhouse, target, destination):
    destination.mkdir(parents=True, exist_ok=True)
    candidates = defaultdict(list)
    for wheel in sorted(Path(source_wheelhouse).glob("*.whl")):
        specificity = target_specificity(wheel.name, target)
        if specificity == 0:
            continue

        candidates[read_wheel_package_name(wheel)].append((specificity, wheel))

    copied = 0
    for package_wheels in candidates.values():
        best_specificity = max(specificity for specificity, _ in package_wheels)
        for specificity, wheel in package_wheels:
            if specificity != best_specificity:
                continue
            shutil.copy2(wheel, destination / wheel.name)
            copied += 1

    if copied == 0:
        raise RuntimeError(f"No compatible wheels found for {target} in {source_wheelhouse}")


def write_lockfile_from_wheelhouse(lockfile, wheelhouse):
    versions = {}
    hashes = defaultdict(set)
    for wheel_path in sorted(wheelhouse.glob("*.whl")):
        package_name, version = read_wheel_metadata(wheel_path)
        existing_version = versions.get(package_name)
        if existing_version is not None and existing_version != version:
            raise RuntimeError(
                f"Multiple versions selected for {package_name}: {existing_version} and {version}"
            )
        versions[package_name] = version
        hashes[package_name].add(sha256_file(wheel_path))

    lines = [
        "# Generated by extensions/graxpert/prepare_wheelhouse.py",
        "# Install the GraXpert root wheel separately with --no-deps, then apply this lockfile.",
        "",
    ]
    for package_name in sorted(versions):
        hash_args = " ".join(
            f"--hash=sha256:{hash_value}" for hash_value in sorted(hashes[package_name])
        )
        lines.append(f"{package_name}=={versions[package_name]} {hash_args}".rstrip())
    lines.append("")
    lockfile.write_text("\n".join(lines), encoding="utf-8")


def prepare_downloaded_wheelhouse(target, staged_package):
    command = [
        sys.executable,
        str(PACKAGE_ROOT / "packaging" / "prepare_wheelhouse.py"),
        "--target",
        target,
        "--wheelhouse",
        str(staged_package / "wheelhouse"),
        "--lockfile",
        str(staged_package / "requirements.lock"),
        "--clean",
    ]
    result = subprocess.run(
        command,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.stdout:
        print(result.stdout, end="", file=sys.stderr)
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        raise RuntimeError(f"prepare_wheelhouse.py failed for {target}")


def build_target(args, target):
    manifest = read_json(PACKAGE_SOURCE / "extension.json")
    with tempfile.TemporaryDirectory() as temp:
        staged_package = Path(temp) / PACKAGE_ID
        copy_package_source(staged_package)

        if args.source_lockfile:
            shutil.copy2(args.source_lockfile, staged_package / "requirements.lock")

        if args.source_wheelhouse:
            copy_existing_wheelhouse(
                args.source_wheelhouse,
                target,
                staged_package / "wheelhouse",
            )
            write_lockfile_from_wheelhouse(
                staged_package / "requirements.lock",
                staged_package / "wheelhouse",
            )
        elif args.download_wheelhouse:
            prepare_downloaded_wheelhouse(target, staged_package)
        else:
            prepare_downloaded_wheelhouse(target, staged_package)

        return build_package(
            staged_package,
            args.output_dir,
            compression_level=args.compression_level,
            runtime_targets=[target],
            asset_name=f"{PACKAGE_ID}-{manifest['version']}-{target}.tar.zst",
        )


def main():
    parser = argparse.ArgumentParser(description="Build GraXpert target-specific package assets.")
    parser.add_argument("--output-dir", default="dist", help="Directory where assets are written")
    parser.add_argument(
        "--target",
        dest="targets",
        action="append",
        choices=TARGETS,
        help="Runtime target to build. Defaults to all staged targets.",
    )
    parser.add_argument("--compression-level", type=int, default=10, help="zstd compression level, 1-19")
    parser.add_argument("--source-wheelhouse", type=Path, help="Existing wheelhouse to filter by target")
    parser.add_argument("--source-lockfile", type=Path, help="Existing requirements.lock to copy into staged assets")
    parser.add_argument(
        "--download-wheelhouse",
        action="store_true",
        help="Download a fresh target wheelhouse with prepare_wheelhouse.py",
    )
    args = parser.parse_args()

    if args.source_wheelhouse and args.download_wheelhouse:
        parser.error("--source-wheelhouse and --download-wheelhouse are mutually exclusive")

    args.output_dir = Path(args.output_dir)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    try:
        assets = [build_target(args, target) for target in (args.targets or TARGETS)]
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(json.dumps(assets, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
